
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : SecondType_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace BondExampleB.Global.SecondType
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public enum SecondTypeVersion
    {
        SecondTypeA,
        SecondTypeB,
        None,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class SecondType
    {
        [global::Bond.Id(0)]
        public SecondTypeVersion SecondTypeVersion { get; set; }

        public SecondType()
            : this("BondExampleB.Global.SecondType.SecondType", "SecondType")
        {}

        protected SecondType(string fullName, string name)
        {
            SecondTypeVersion = SecondTypeVersion.None;
        }
    }
} // BondExampleB.Global.SecondType
