
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : SecondTypeA_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace BondExampleA.Global
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.1.0")]
    public partial class SecondTypeA
        : SecondType
    {
        [global::Bond.Id(0)]
        public int id { get; set; }

        [global::Bond.Id(1)]
        public string name { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.blob))]
        public decimal foo { get; set; }

        [global::Bond.Id(3)]
        public string bar { get; set; }

        public SecondTypeA()
            : this("BondExampleA.Global.SecondTypeA", "SecondTypeA")
        {}

        protected SecondTypeA(string fullName, string name)
        {
            this.name = "";
            foo = new decimal();
            bar = "";
        }
    }
} // BondExampleA.Global
